(defproject knotlog "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [environ "1.2.0"]
                 [clj-jgit "1.0.2"]
                 [com.taoensso/timbre "6.6.1"]
                 [org.slf4j/jul-to-slf4j "2.0.16"]
                 [org.eclipse.jetty/jetty-slf4j-impl "11.0.15"]
                 [org.immutant/scheduling "2.1.10"]
                 [org.clojure/java.jdbc "0.7.12"]
                 [com.github.seancorfield/honeysql "2.2.861"]
                 [org.postgresql/postgresql "42.3.2"]
                 [metosin/reitit "0.5.15"]
                 [ring/ring-jetty-adapter "1.9.5"]
                 [ring-cors "0.1.13"]
                 [buddy/buddy-auth "3.0.323"]
                 [buddy/buddy-sign "3.5.351"]
                 [clj-time "0.15.2"]
                 [tick/tick "0.7.5"]]
  :plugins [[lein-environ "1.2.0"]
            [lein-pprint "1.3.2"]]
  :source-paths ["src"]
  :main knotlog.clj.main)
